name: Automated tests

on:
    workflow_dispatch:
      inputs:
        deployment_target:
          description: Choose promt
          required: true
          default:
          type: choice
          options:
            - first_promt
            - second_promt
            - third_promt

        

jobs:
    test: 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.12"
            - name: Install Chrome
              run: sudo apt-get install google-chrome-stable
            - name: install dependencies
              run: pip install -r requirements.txt
            - name: first_promt
              if: 'github.event.inputs.deployment_target == "first_promt"'
              run: pytest -m promt1
            - name: second_promt
              if: 'github.event.inputs.deployment_target == "second_promt"'
              run: pytest -m promt2
            - name: third_promt
              if: 'github.event.inputs.deployment_target == "third_promt"'
              run: pytest -m promt3