name: Automated tsts

on:
    workflow_run:
      workflows: [Run Tests]
      types:
        - completed
        

jobs:
    test: 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.12"
            - name: Install Chrome
              run: sudo apt-get install google-chrome-stable
            - name: install dependencies
              run: pip install -r requirements.txt
            - name: all_test
              run: pytest
            # - name: Run tests
            #   run: pytest
        